DROP TABLE Cleaning ;
DROP TABLE StaffMember  ;
DROP TABLE Apartment ;
DROP TABLE CorpClient ;
DROP TABLE Inspecting ;
DROP TABLE Inspector ;
DROP TABLE Managerphone ; 
DROP TABLE Manager ;
DROP TABLE Building ; 